-- MySQL Script generated by MySQL Workbench
-- Tue Apr  3 17:17:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kino` DEFAULT CHARACTER SET utf8 ;
USE `kino` ;

-- -----------------------------------------------------
-- Table `kino`.`adres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kino`.`adres` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ulica` VARCHAR(30) NOT NULL,
  `nr_domu` SMALLINT(6) NOT NULL,
  `miasto` VARCHAR(45) NOT NULL,
  `kod_pocztowy` INT(11) NOT NULL,
  `wojewodztwo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kino`.`klient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kino`.`klient` (
  `id` INT(11) NOT NULL,
  `imie` VARCHAR(15) NOT NULL,
  `nazwisko` VARCHAR(25) NOT NULL,
  `nr_telefonu` INT(11) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE (`mail`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kino`.`rezerwacja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kino`.`rezerwacja` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data_rezerwacji` DATETIME NOT NULL,
  `liczba_biletow` INT(11) NOT NULL,
  `klient_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `klient_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_rezerwacja_klient1_idx` (`klient_id` ASC),
  CONSTRAINT `fk_rezerwacja_klient1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `kino`.`klient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kino`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kino`.`film` (
  `tytul` VARCHAR(45) NOT NULL,
  `dlugosc` FLOAT NOT NULL,
  `rezyser` VARCHAR(25) NOT NULL,
  `data_produkcji` DATE NULL DEFAULT NULL,
  `kategoria` VARCHAR(20) NULL DEFAULT NULL,
  `ocena` FLOAT NULL DEFAULT NULL,
  `ograniczenia_wiekowe` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`tytul`),
  UNIQUE INDEX `tytuł_UNIQUE` (`tytul` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kino`.`kino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kino`.`kino` (
  `nazwa` VARCHAR(45) NOT NULL,
  `liczba_sal` TINYINT(4) NOT NULL,
  `adres_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`nazwa`),
  INDEX `fk_kino_adres1_idx` (`adres_id` ASC),
  CONSTRAINT `fk_kino_adres1`
    FOREIGN KEY (`adres_id`)
    REFERENCES `kino`.`adres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kino`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kino`.`sala` (
  `numer` INT(11) NOT NULL,
  `liczba_miejsc` SMALLINT(6) NOT NULL,
  `kino_nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numer`, `kino_nazwa`),
  INDEX `fk_sala_kino1_idx` (`kino_nazwa` ASC),
  CONSTRAINT `fk_sala_kino1`
    FOREIGN KEY (`kino_nazwa`)
    REFERENCES `kino`.`kino` (`nazwa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kino`.`seans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kino`.`seans` (
  `id` INT(11) NOT NULL,
  `data` DATETIME NOT NULL,
  `sala_numer` INT(11) NOT NULL,
  `cena` DOUBLE NOT NULL,
  `sala_kino_nazwa` VARCHAR(45) NOT NULL,
  `film_tytul` VARCHAR(45) NOT NULL,
  `dlugosc_reklam` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_seans_sala1_idx` (`sala_numer` ASC, `sala_kino_nazwa` ASC),
  INDEX `fk_seans_film1_idx` (`film_tytul` ASC),
  CONSTRAINT `fk_seans_film1`
    FOREIGN KEY (`film_tytul`)
    REFERENCES `kino`.`film` (`tytul`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seans_sala1`
    FOREIGN KEY (`sala_numer` , `sala_kino_nazwa`)
    REFERENCES `kino`.`sala` (`numer` , `kino_nazwa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kino`.`bilet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kino`.`bilet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nr_siedzenia` INT(11) NOT NULL,
  `rzad` INT(11) NOT NULL,
  `ulga` ENUM('25%', '20%') NULL DEFAULT NULL,
  `rezerwacja_id` INT(11) NULL DEFAULT NULL,
  `seans_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_bilet_rezerwacja1_idx` (`rezerwacja_id` ASC),
  INDEX `fk_bilet_seans1_idx` (`seans_id` ASC),
  CONSTRAINT `fk_bilet_rezerwacja1`
    FOREIGN KEY (`rezerwacja_id`)
    REFERENCES `kino`.`rezerwacja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bilet_seans1`
    FOREIGN KEY (`seans_id`)
    REFERENCES `kino`.`seans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kino`.`pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kino`.`pracownik` (
  `pesel` VARCHAR(11) NOT NULL,
  `imie` VARCHAR(15) NOT NULL,
  `nazwisko` VARCHAR(25) NOT NULL,
  `data_urodzenia` DATE NOT NULL,
  `nr_telefonu` INT(11) NOT NULL,
  `plec` ENUM('M', 'K') NOT NULL,
  `pensja` INT(11) NOT NULL,
  PRIMARY KEY (`pesel`),
  UNIQUE INDEX `pesel_UNIQUE` (`pesel` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kino`.`etat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kino`.`etat` (
  `kino_nazwa` VARCHAR(45) NOT NULL,
  `pesel` VARCHAR(11) NOT NULL,
  `wymiar_godzinowy` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`kino_nazwa`, `pesel`),
  INDEX `fk_kino_has_pracownik_pracownik1_idx` (`pesel` ASC),
  INDEX `fk_kino_has_pracownik_kino1_idx` (`kino_nazwa` ASC),
  CONSTRAINT `fk_kino_has_pracownik_kino1`
    FOREIGN KEY (`kino_nazwa`)
    REFERENCES `kino`.`kino` (`nazwa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kino_has_pracownik_pracownik1`
    FOREIGN KEY (`pesel`)
    REFERENCES `kino`.`pracownik` (`pesel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
